data_directory:
    data/example_project

# Sequences with length < min length will be removed. (int)
sequence_min_length:
    27000

# Remove sequences whose corresponding pango lineages are not in the provided CoVizu time-scaled tree.
# CoVizu -> https://filogeneti.ca/CoVizu/
# The "covizu_tree" parameter is mainly designed for the workflow for covSampler web application.
# In general, keep it = "False".
covizu_tree:
    False

# Return genbank accession.
# The "genbank_accession" parameter is designed for the workflow for covSampler web application.
# Please keep it = "False".
genbank_accession:
    False

# This pipeline consists of two parts: 1) data processing and 2) subsampling.
# 1) Before subsampling, you should process the data for subsampling.
#    In this stage, please set "start_subsampling" parameter = "False".
# 2) After data processing, you can perform subsampling.
#    In this stage, please set "start_subsampling" parameter = "True".
start_subsampling:
    False

# Subsampling
subsampling:
    # Subsamples output path
    output_path:
        results/example_project/subsamples.txt
    
    # Description recorded in the output file (False or str)
    description:
        # False
        Example subsampling

    # Location of subsamples
    # Format: <Continent>/(<Country>)/(<Division>)
    # Examples: Global, Europe, Europe/United Kingdom, Europe/United Kingdom/England
    # See all available values in "<data_directory>/args/locations.txt".
    location:
        Global
    
    # Date range of subsamples
    # Format: YYYY-MM-DD
    # See all available values in "<data_directory>/args/dates.txt".
    date_start:
        2020-01-01
    date_end:
        2022-01-01
    
    # Variants of subsamples
    #
    # NONSPECIFIC -> False
    #
    # LINEAGE
    # Lineage format -> a) WHO: - Lineage/WHO/<WHO clade>
    #                   b) Pango lineage: - Lineage/Pango_lineage/<Pango lineage>
    #                   c) Nextstrain clade: - Lineage/Nextstrain_clade/<Nextstrain clade>
    # Lineage examples -> a) WHO: - Lineage/WHO/Alpha
    #                     b) Pango lineage: - Lineage/Pango_lineage/B.1.1.7
    #                     c) Nextstrain clade: - Lineage/Nextstrain_clade/20I (Alpha, V1)
    #
    # SITE
    # Site format -> b) Nucleotide: - Site/Nucleotide/<ref><site><mut>
    #                a) Amino acid: - Site/Amino_acid/<gene>:<ref><site><mut>  Note: "-" = deletion, "*" = stop
    #                
    # Site examples -> a) Nucleotide: - Site/Nucleotide/A23403G
    #                  b) Amino acid: - Site/Amino_acid/S:N501Y, - Site/Amino_acid/S:H69-, - Site/Amino_acid/ORF7a:Q62*
    #
    # ** SARS-CoV-2 Genome Map
    # -------------------------------------------------------------------------------
    # |    Gene Name     |   Start   |   End   |   Length   |   Amino Acid Length   |
    # -------------------------------------------------------------------------------
    # |   ORF1a          |   266     |  13468  |   13203    |   4401                |
    # |   ORF1b          |   13468   |  21555  |   8088     |   2696                |
    # |   S              |   21563   |  25384  |   3822     |   1274                |
    # |   ORF3a          |   25393   |  26220  |   828      |   276                 |
    # |   E              |   26245   |  26472  |   228      |   76                  |
    # |   M              |   26523   |  27191  |   669      |   223                 |
    # |   ORF6           |   27202   |  27387  |   186      |   62                  |
    # |   ORF7a          |   27394   |  27759  |   366      |   122                 |
    # |   ORF7b          |   27756   |  27887  |   132      |   44                  |
    # |   ORF8           |   27894   |  28259  |   366      |   122                 |
    # |   ORF9b          |   28284   |  28577  |   294      |   98                  |
    # |   N              |   28274   |  29533  |   1260     |   420                 |
    # -------------------------------------------------------------------------------
    #
    # See all available values in "<data_directory>/args/who_variants.txt",
    #                             "<data_directory>/args/pango_lineages.txt",
    #                             "<data_directory>/args/nextstrain_clades.txt",
    #                             "<data_directory>/args/nucleotide.txt",
    #                             "<data_directory>/args/amino_acid.txt".
    variants:
        # False
        - Lineage/WHO/Alpha
        - Lineage/Nextstrain_clade/20I (Alpha, V1)
        - Lineage/Pango_lineage/B.1.1.7
        - Site/Nucleotide/A23403G
        - Site/Amino_acid/S:N501Y
        - Site/Amino_acid/S:H69-
        - Site/Amino_acid/ORF7a:Q62*

    # Number of subsamples (int)
    size:
        500
    
    # Subsampling characteristic (Representative or Comprehensive)
    characteristic:
        Representative
    
    # Seed number for pseudorandom subsampling (int)
    seed:
        2019

    # Temporally even subsampling (bool)
    temporally_even:
        False
